Feature/footer pages
YummYume/StackUp pull request #20
Opened 2023-02-24 19:36 UTC by Teyo01

2023-02-24 19:40 UTC, LeoBruant commented on templates/info/about_us.html.twig
> +{% endblock %}
```suggestion
{% endblock %}

```

2023-02-24 19:40 UTC, LeoBruant commented on templates/legal/cookie_policy.html.twig
> +{% endblock %}
```suggestion
{% endblock %}

```

2023-02-24 20:20 UTC, YummYume requested changes

2023-02-24 20:20 UTC, YummYume commented on translations/messages+intl-icu.en.yaml
> +common.upload.click_or_drop: Drag and drop a file or click t    o browse
```suggestion
common.upload.click_or_drop: Drag and drop a file or click to browse
```

2023-02-24 20:20 UTC, YummYume commented on translations/messages+intl-icu.en.yaml
> +page.contact.presentation: to contact us, please send us an email at challenge@stack_up.tech
```suggestion
page.contact.presentation: to contact us, please send us an email at contact@stack-up.tech
```

2023-02-24 20:20 UTC, YummYume commented on .gitignore
> +
```suggestion
```

2023-02-24 20:20 UTC, YummYume commented on .gitignore
> +
```suggestion
```

2023-02-24 20:20 UTC, YummYume commented on templates/legal/cookie_policy.html.twig
> +    <p><strong>{{ "page.cookie_policy.what_are_cookies.title"|trans }}</strong></p>
Du coup apparemment ça serait mieux de mettre des br si c'est juste pour sauter des lignes

2023-02-24 20:21 UTC, LeoBruant commented on templates/legal/privacy_policy.html.twig
> +    <h1>{{ "page.privacy_policy.presentation.title"|trans }}</h1>
Attention, dans le block `main_title` ca rajoute deja un h1 donc faut pas remettre de h1

2023-02-26 16:12 UTC, LeoBruant approved these changes

2023-02-26 19:30 UTC, YummYume approved these changes

2023-02-26 20:01 UTC, merged